---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  sudo: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }

    ## Scripting / Language support
    - { role: php-fpm, nginx_site_template: "symfony2-site.j2" }

    ## Install Composer in the box
    - { role: composer }

# If needed, you can specify your own tasks, here is an example :
  tasks:
    - name: install backend vendors
      shell: cd {{ project_directory }} && composer.phar --quiet install
